# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bce7c47a5c6f8f2ba8add9e9e4262aa30d8e58ca77a0b65e928155ae4dee314b380d8d15d9e85069e84385de1dbdea819499df1e829b0d119b541305b8ee2b94

test:
  secret_key_base: 4af00ad33b52d789902822a622cdbafeb345b8b6a9be73a25403334255aa488d3ec06e36965c41ed4f5d2aaf71fcb7b9900485e1fbd6720928b3cbb33dfdcca3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
